export default {
    token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXYiOiJlbmMyOGo2MCIsImlhdCI6MTU1MTIxNTgxMiwianRpIjoiNWM3NWFjYzQ3N2QwNzViZTIzYmVmMjU2IiwidXNyIjoibWVqaXNvbiJ9.iU-AfqdBuiQ3cfaSi1x-McUyJ5j-oLGTfT8GtA8rDSI'
}